### ISSUE TITLE
callbacks on `fileNames` are not triggered

### ISSUE THREAD

**Issue by drahnreb** [np-8/dash-uploader#1]
`pip list | grep 'dash'`

dash                      1.11.0 
dash-bootstrap-components 0.10.0 
dash-core-components      1.9.1  
dash-html-components      1.0.3  
dash-renderer             1.4.0  
dash-table                4.6.2  
dash-uploader             0.1.0 

The `display_files`-function of the MWE is not called after each upload.
It does work for the first time, but any successive call won't update the Output.

Files are uploaded to `UPLOAD_FOLDER` and the Complete Label is also changed.

Strangely it seems like no component prop is changed though.

**Comment by np-8** [comment]
Thanks for reporting the issue! If I understood correctly, the problem was in python, the `fileNames` is a list which will not "change" (the id is the same), if a string is appended into it. Therefore, I added another property `isCompleted` that is a boolean and tells when the upload is complete. The `fileNames` is still a list of strings.  Maybe someday there will be a possibility for the user to select multiple files to be uploaded. Until then, the length of the `fileNames` will always be one.

I put the changes into the v.0.1.1 (commit https://github.com/np-8/dash-uploader/commit/1ea6096fd57d1d74533a9654686786691f62c89f) and updated the example in the README.md. 

Hope it works for you now!
