### ISSUE TITLE
Request function to delete the files after session ends or some period of time after the upload

### ISSUE THREAD

**Issue by ougx** [np-8/dash-uploader#10]
Thanks for this amazing tool. 

To avoid the increase of storage on the server, I need to remove the files uploaded by users.

Can this be implemented? Or is there a way to do it (from python or bash). Thanks!

**Comment by np-8** [comment]
I'm glad you're liking it! 

I understand that having a simple way of removing the uploaded files makes sense. Unfortunately I haven't been playing around with my dash project for a while and I don't have a good general solution for it from the top of my head. The simplest would be to just call `os.unlink` or similar with the correct path. The path should be saved somewhere for the duration of the session, for example. So for an app with multiple concurrent users there must be some sort of user session handling logic in the application (e.g. using cookies). I also think some special care should be taken so that user A can not remove any files uploaded by user B. If one of the users would remove the session id (e.g. empty cookies), then there should be some application logic for user authentication. 

For simple "one user on same machine as server" use case removing uploaded files would be super-simple. 

I guess that for more complex use cases, implementing removal of uploaded files correctly will take quite an effort, and needs probably some additional authorization / authentication / session handling. Therefore, for now, I think this functionality should remain out-of-scope for dash-uploader. 

What I would myself do, if possible, is to just run a timed script that removes all the files that can be removed from the upload folder (e.g. /myapp/uploads). For example, I would check the timestamp of each uploaded file and remove everything older than 4 hours. And just after any file upload, if there is anything needed to be saved for longer period of time, I would put that into separate folder, like /myapp/data.

**Comment by ougx** [comment]
Thanks, I guess I will just do the scheduled removal for files that are older than some tome.
